blog/urls.py
from django.urls import path, register_converter

from blog import views
from . import converters

app_name = 'blog'
register_converter(converters.FourDigitYearConverter, 'yyyy')
urlpatterns = [
    path('', views.PostList.as_view(), name='post_list'),
    path('detail/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
    path('detail/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post_delete'),
    path("detail/<int:pk>/edit/", views.post_edit, name="post_edit"),
    path('comment/<int:pk>/', views.comment_create, name='comment_create'),
    path('comment/<int:pk>/edit/', views.comment_edit, name='comment_edit'),
    path('reply/<int:comment_pk>/', views.reply_create, name='reply_create'),
    path("new/", views.post_new, name="post_new"), 
    # path("<int:post_id>/", views.post_detail, name="post_detail"),
    # path("<int:post_id>/comments/new/", views.comment_new, name="comment_new"),
    # path("<int:snippet_id>/comments/<int:comment_id>", views.comment_detail, name="comment_detail"),
    # path("<yyyy:year>/", views.year_archive),
    # path("hello/", views.hello, name="hello"),
    # # path("users/", views.user_list, name="user_list"),
    # # path("users/<str:name>", views.user_detail, name="user_detail"),
    # path("hello/", views.hello, name="hello"),
    
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import top

handler400 = 'blog.views.handler400'
handler403 = 'blog.views.handler403'
handler404 = 'blog.views.handler404'
handler500 = 'blog.views.handler500'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', top, name='top'),
    path('posts/', include("blog.urls")),
    path('accounts/', include("allauth.urls")),
    # path('accounts/', include("accounts.urls")),
]

djangosnippets/urls.py
from django.contrib import admin
from django.urls import path, include
from snippets.views import top

handler400 = 'snippets.views.handler400'
handler403 = 'snippets.views.handler403'
handler404 = 'snippets.views.handler404'
handler500 = 'snippets.views.handler500'
urlpatterns = [
    path('', top, name='top'),
    path('snippets/', include("snippets.urls")),
    path('accounts/', include("accounts.urls")),
    path('admin/', admin.site.urls),
]

blog/models.py
from django.conf import settings
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField('タイトル', max_length=255)
    content = models.TextField('説明', blank=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
                                   verbose_name="投稿者",
                                   on_delete=models.CASCADE)
    created_at = models.DateTimeField("投稿日", auto_now_add=True)
    updated_at = models.DateTimeField("更新日", auto_now=True)
    is_updated = models.BooleanField(help_text='編集済みならTrue', default=False)
    
    class Meta:
        db_table = 'posts'
    def __str__(self):
        return f'{self.pk} {self.title}'
    
    
# class Comment(models.Model):
#     text = models.TextField('本文', blank=False)
#     commented_at = models.DateTimeField("投稿日", auto_now_add=True)
#     commented_to = models.ForeignKey(Post, verbose_name="記事", on_delete=models.CASCADE, related_name='comments')
#     commented_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
#                                    verbose_name="投稿者",
#                                    on_delete=models.CASCADE)
#     class Meta:
#         db_table = 'comments'
#     def __str__(self):
#         return f'{self.pk} {self.text}'
    
class Comment(models.Model):
    text = models.TextField('コメント内容')
    post = models.ForeignKey(Post, verbose_name='対象記事', on_delete=models.CASCADE)
    parent = models.ForeignKey('self', verbose_name='親コメント', null=True, blank=True, on_delete=models.CASCADE)
    commented_at = models.DateTimeField("投稿日", auto_now_add=True)
    commented_by = models.ForeignKey(settings.AUTH_USER_MODEL, 
                                   verbose_name="投稿者",
                                   on_delete=models.CASCADE)
    updated_at = models.DateTimeField("更新日", auto_now=True)
    is_updated = models.BooleanField(help_text='編集済みならTrue', default=False)
    def __str__(self):
        return self.text[:10]
    class Meta:
        db_table = 'comments'
class Tag(models.Model):
    name = models.CharField("タグ名", max_length=32)
    posts = models.ManyToManyField(Post, related_name='tags', related_query_name='tag')
    class Meta:
        db_table = "tags"
    
    def __str__(self):
        return f'{self.pk} {self.name}'
    

blog/forms.py
from django import forms

from blog.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content',)
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

blog/views.py
from django import forms
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth import get_user_model
from django.views import generic
from django.views.generic.edit import DeleteView
from .models import Post, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_safe, require_http_methods, require_GET
from blog.forms import PostForm, CommentForm
from django.urls import reverse_lazy

# コメント、返信フォーム
# CommentForm = forms.modelform_factory(Comment, fields=('text', ))
# User = get_user_model()

class PostList(generic.ListView):
    """記事一覧"""
    model = Post


class PostDetail(generic.DetailView):
    """記事詳細"""
    model = Post

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # どのコメントにも紐づかないコメント=記事自体へのコメント を取得する
        context['comment_form'] = CommentForm
        context['comment_list'] = self.object.comment_set.filter(parent__isnull=True)
        return context
class PostDeleteView(DeleteView):
    template_name = "blog/post_delete.html"
    model = Post
    success_url = reverse_lazy("blog:post_list")

@login_required
@require_http_methods(["GET", "POST", "HEAD"])
def comment_create(request, pk):
    """記事へのコメント作成"""
    post = get_object_or_404(Post, pk=pk)
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        comment = form.save(commit=False)
        comment.post = post
        print(request.user)
        comment.commented_by = request.user
        comment.save()
        return redirect('blog:post_detail', pk=post.pk)

    context = {
        'form': form,
        'post': post
    }
    return render(request, 'blog/comment_form.html', context)


@login_required
@require_http_methods(["GET", "POST", "HEAD"])
def reply_create(request, comment_pk):
    """コメントへの返信"""
    comment = get_object_or_404(Comment, pk=comment_pk)
    post = comment.post
    form = CommentForm(request.POST or None)

    if request.method == 'POST':
        reply = form.save(commit=False)
        reply.parent = comment
        reply.post = post
        reply.commented_by = request.user
        reply.save()
        return redirect('blog:post_detail', pk=post.pk)

    context = {
        'form': form,
        'post': post,
        'comment': comment,
    }
    return render(request, 'blog/comment_form.html', context)

# from django.shortcuts import render, get_object_or_404, redirect
# from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseForbidden, HttpResponseNotFound, HttpResponseNotAllowed
# from blog.models import Snippet, Comment
# from blog.forms import PostForm, CommentForm
# from django.views.decorators.http import require_safe, require_http_methods, require_GET
# from django.http import JsonResponse
# from django.template.response import TemplateResponse
from urllib.parse import quote
# # Create your views here.

@require_safe
def top(request):
    posts = Post.objects.all()
    context = {"posts": posts}
    return render(request, "blog/top.html", context) 
# def top(request):
#     return HttpResponse(b"Hello World")

@login_required
@require_http_methods(["GET", "POST", "HEAD"])
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid(): 
            post = form.save(commit=False)
            post.created_by = request.user
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, "blog/post_new.html", {'form': form})

@login_required
@require_http_methods(["GET", "POST", "HEAD"])
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if post.created_by_id != request.user.id:
        return HttpResponseForbidden("この記事の編集は許可されていません")
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            post.is_updated = True
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, "blog/post_edit.html", {'form': form})
@login_required
@require_http_methods(["GET", "POST", "HEAD"])
def comment_edit(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    if comment.commented_by_id != request.user.id:
        return HttpResponseForbidden("このコメントの編集は許可されていません")
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            comment.is_updated = True
            comment.save()
            return redirect('blog:post_detail', pk=comment.post.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, "blog/comment_edit.html", {'form': form})

# @require_safe
# def post_detail(request, post_id, comments):
#     post = get_object_or_404(Post, pk=post_id)
#     context = {'post': post, 'comment_form': CommentForm, 'comments': comments}
#     return render(request, 'blog/post_detail.html', context)
# @require_safe
# def snippet_detail(request, snippet_id):
#     try:
#         snippet = Snippet.objects.get(id=snippet_id)
#     except Snippet.DoesNotExist:
#         return HttpResponseNotFound("Snippet is not found")
#     return render(request, 'snippets/snippet_detail.html', {'snippet': snippet})
# @login_required
# @require_http_methods(["GET", "POST", "HEAD"])
# def comment_new(request, post_id):
#     if request.method == 'POST':
#         post = get_object_or_404(Post, pk=post_id)
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.post = post
#             comment.commented_by = request.user
#             # comment.commented_to = post
#             comment.save()
#             # comments = Comment.objects.filter(commented_to=target_snippet)
#             # context = { 'comments': comments }
#             return redirect('blog:post_detail', post_id=post.pk)
#     else:
#         form = CommentForm()
#     return render(request, "blog/comment_new.html", {'form': form})

# @require_safe
# def comment_detail(request, snippet_id, comment_id):
#     comment = get_object_or_404(Comment, pk=comment_id)
#     context = {'comment': comment}
#     return render(request, 'snippets/comment_detail.html', context)

# def snippet_list_api(request):
#     snippets = Snippet.objects.all()
#     return JsonResponse({"snippets": snippets})


# @require_GET
# def hello(request):
#     context = {'username': 'c-bata'}
#     return TemplateResponse(request, 'hello.html', context)
# def hello(request):
#     if request.method != "GET":
#         # GETメソッド以外は、405 Method Not Allowedを返す。
#         response = HttpResponseNotAllowed(["GET"])
#         return response
#     context = {'username': 'c-bata'}
#     return TemplateResponse(request, 'hello.html', context)

# def hello(request):
#     response = HttpResponse(b"Hello World", status=200)
#     response['Cache-Control'] = 'max-age=3600' # ヘッダーのセット
#     return response

def handler400(request, exception):
    return render(request, 'errors/400.html', {}, status=400)
def handler403(request, exception):
    return render(request, 'errors/403.html', {}, status=403)
def handler404(request, exception):
    context = {"request_path": quote(request.path)}
    return render(request, 'errors/404.html', context, status=404)
def handler500(request):
    return render(request, 'errors/500.html', {}, status=500)

blog/templates/blog/aaapost_detail.html
{% extends 'base.html' %}

{% block extraheader %}
{% endblock %}

{% block main %}
<main id="main">
  <div class="container">
    <h2>{{ post.title }} by {{ post.created_by.username }}</h2>

    <div class="post-date">
      投稿日： {{ post.created_at | date:"DATETIME_FORMAT" }}
      {% if user.is_authenticated and post.created_by_id == user.id %}
      <a href="{% url 'blog:post_edit' post.id %}">編集</a>
      {% endif %}
    </div>
    <p>{{ post.content | urlize}}</p>
    <div class="comments-area" >
      <h2>コメント一覧</h2>
      {% if post.comments.all %}
      <table class="table">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>投稿日</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          {% for comment in post.comments.all %}
          <tr>
            <th>{{ comment.commented_by.username }}</th>
            <th>{{ comment.commented_at }}</th>
            <th><a href="{% url 'comment_detail' post.id comment.id %}">{{ comment.text }}</a></th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>コメントはまだ寄せされていません。</p>
      {% endif %}
    <!-- コメント作成フォームを表示 -->
    <div class="comment-form">
      <h2>コメント投稿</h2>
      <form action='{% url "blog:comment_create" post.id %}' method="post">
        {% csrf_token %}
        {{ comment_form }}
        <div>
          <button class="btn btn-primary"  type="submit">送信</button>
        </div>
      </form>
    {% comment %} </div>
      <a class="btn btn-primary" href="{% url 'comment_new' snippet.id %}">コメントする</a>
    </div> {% endcomment %}
  </div>
</main>
{% endblock %}

blog/templates/blog/comment_detail.html
{% extends 'base.html' %}

{% block extraheader %}
{% endblock %}

{% block main %}
<main id="main">
  <div class="container">
    <h2>{{ comment.text }} by {{ comment.commented_by.username }}</h2>

    <div class="snippet-date">
      投稿日： {{ comment.commented_at | date:"DATETIME_FORMAT" }}
      {% if user.is_authenticated and comment.commented_by_id == user.id %}
      {% comment %} <a href="{% url 'comment_edit' comment.id %}">編集</a> {% endcomment %}
      {% endif %}
    </div>
    <p>{{ comment.text | urlize}}</p>
    <div class="comments-area" >
      <h2>コメント一覧</h2>
      {% if comment.comments.all %}
      <table class="table">
        <thead>
          <tr>
            <th>投稿者</th>
            <th>投稿日</th>
            <th>内容</th>
          </tr>
        </thead>
        <tbody>
          {% for comment in comment.comments.all %}
          <tr>
            <th>{{ comment.commented_by.username }}</th>
            <th>{{ comment.commented_at }}</th>
            <th><a href="{% url 'comment_detail' comment.id %}">{{ comment.text }}</a></th>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <p>コメントはまだ寄せされていません。</p>
      {% endif %}
      
      {% comment %} <a class="btn btn-primary" href="{% url 'comment_new' comment.id %}">コメントする</a> {% endcomment %}
    </div>
  </div>
</main>
{% endblock %}

blog/templates/blog/comment_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
<main id="main">
  <div class="container">
<h1>コメントの編集</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="保存" %}
  {% comment %} {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">保存</button> {% endcomment %}
</form>
</div>
</main>
{% endblock %}

blog/templates/blog/comment_form.html
{% extends 'base.html' %}

{% block main %}
<main id="main">
    <div class="container">
    <section class="section">
        <h1>コメントの投稿</h1>
        <div class="container">
            <form action="" method="POST">
                {{ form.as_p }}
                {% csrf_token %}
                <button type="submit">送信</button>
            </form>
        </div>
    </section>
</div>
</main>
{% endblock %}

blog/templates/blog/comment_new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
<main id="main">
  <div class="container">
<h1>コメントの投稿</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="コメントを送信" %}
  {% comment %} {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">登録</button> {% endcomment %}
</form>
</div>
</main>
{% endblock %}

blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block main %}
<main id="main">
    <section class="section">
        <div class="container">
            <form method="post">
                {% csrf_token %}
                <p>この記事を削除しますか？</p>
                <table class="table table-sm table-bordered table-responsive">
                    <tbody>
                        <tr>
                            <th>ID</th>
                            <td>{{ object.id }}</td>
                        </tr>
                        <tr>
                            <th>記事名</th>
                            <td>{{ object.title }}</td>
                        </tr>
                    </tbody>
                </table>
                <input class="btn btn-danger" type="submit" value="削除する">
            </form>
        </div>
    </section>
<main>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block main %}
<main id="main">
    <section class="section">
        <div class="container">
            <a href="{% url 'blog:post_list' %}">記事一覧へ</a>
            <hr>

            <h1 class="title">{{ post.title }} by {{ post.created_by.username }}</h1>
            <small>{{ post.created_at }}</small>
            {% if post.is_updated %}
            <small> {{ post.updated_at }}編集済み</small>
            {% endif %}
            {% if user.is_authenticated and post.created_by_id == user.id %}
            <a href="{% url 'blog:post_edit' post.id %}">編集する</a>
            <a href="{% url 'blog:post_delete' post.id %}">削除する</a>

            {% endif %}
            <div class="content">
                {{ post.content | linebreaks }}
            </div>
            {% comment %} <a href="{% url 'blog:comment_create' post.pk %}">コメントする</a> {% endcomment %}

            <hr>
            <h2 class="title is-5">コメント一覧</h2>
            {% if comment_list %}
            {% for comment in comment_list %}
                <div class="recursive-box">
                    <p>{{ comment.pk }} {{ comment.commented_by.username }}
                        <small>{{ comment.commented_at }}</small>
                        {% if comment.is_updated %}
                        <small> {{ comment.updated_at }}編集済み</small>
                        {% endif %}
                        {% if user.is_authenticated and comment.commented_by_id == user.id %}
                        <a href="{% url 'blog:comment_edit' comment.id %}">編集する</a>
                        {% endif %}
                    </p>
                    <p>{{ comment.text }}
                    </p>
                    <a href="{% url 'blog:reply_create' comment.pk %}">返信する</a>
                    {% with reply_list=comment.comment_set.all %}
                        {% include 'includes/main/blog/reply.html' %}
                    {% endwith %}
                </div>
            {% endfor %}
            {% else %}
            <p>まだコメントはありません</p>
            {% endif %}
                <!-- コメント作成フォームを表示 -->
    <div class="comment-form">
    <h2>コメント投稿</h2>
    <form action='{% url "blog:comment_create" post.pk %}' method="post">
        {% csrf_token %}
        {{ comment_form }}
        <div>
        <button class="btn btn-primary"  type="submit">送信</button>
        </div>
    </form>
    </div>
    </section>
<main>
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
<main id="main">
  <div class="container">
<h1>記事の編集</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="保存" %}
  {% comment %} {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">保存</button> {% endcomment %}
</form>
</div>
</main>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block main %}
<main id="main">
  <div class="container">
    {% if post_list %}
    <table class="thread-table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>作成日</th>
          <th>作成者</th>
        </tr>
      </thead>
      <tbody>
        {% for post in post_list %}
        <tr>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></th>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.created_at }}</a></td>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.created_by.username }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>記事はまだ投稿されていません。</p>
    {% endif %}
    {% comment %} {% for post in post_list %}
        <a href="{% url 'blog:post_detail' post.pk %}">
            <div class="box">
                <p>{{ post.title }} {{ post.created_at }} {{ post.created_by.username }}</p>
            </div>
        </a>
    {% endfor %} {% endcomment %}
  </div>
</main>
{% endblock %}

blog/templates/blog/post_new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block main %}
<main id="main">
  <div class="container">
<h1>記事を作成</h1>
<form method="post">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% bootstrap_button button_type="submit" content="作成" %}
  {% comment %} {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">登録</button> {% endcomment %}
</form>
</div>
</main>
{% endblock %}

blog/templates/blog/top.html
{% extends 'base.html' %}

{% load django_bootstrap5 %}
{% block main %}
{% comment %} {% include "includes/header/header.html" %} {% endcomment %}
<main id="main">
  <div class="container">
    <div class="welcome">
      <h1 class="title">ようこそMaeplegoへ！</h1>
      <p class="subtitle"></p>
      <a class="btn btn-primary" href="{% url 'blog:post_new' %}">記事を作成する</a>
    </div>
    {% if posts %}
    <table class="thread-table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>作成日</th>
          <th>作成者</th>
        </tr>
      </thead>
      <tbody>
        {% for post in posts %}
        <tr>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></th>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.created_at }}</a></td>
          <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.created_by.username }}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>記事はまだ投稿されていません。</p>
    {% endif %}
  </div>
  {% include "includes/main/blog/pickup.html" %}
  {% include "includes/main/blog/posts.html" %}
  {% include "includes/main/blog/contact.html" %}
</main>
{% endblock %}